version: '3.8'

services:
  db:
    image: postgres:15
    container_name: twitter_clone_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: twitter_clone_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://admin:admin@db:5432/admin
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./app/media:/app/media

volumes:
  postgres_data: