[tool.black]
exclude = '''
/(
    migrations
)/
'''

[tool.isort]
profile = "black"
line_length = 88 # чтобы совпадало с black
skip = ["migrations"]

[tool.flake8]
max-line-length = 88
ignore = ["E203", "W503"]

[tool.mypy]
plugins = []

["mypy-aiofiles.*"]
ignore_missing_imports = true