"""Фикс relationships в модели Likes

Revision ID: 8570a62adfbf
Revises: f6e2dc6e7307
Create Date: 2025-07-07 13:16:04.153220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8570a62adfbf'
down_revision: Union[str, Sequence[str], None] = 'f6e2dc6e7307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
