"""фикс релатионшип на модлях юзер и твитс

Revision ID: e818bc5a9699
Revises: 0904c596e780
Create Date: 2025-07-07 13:56:05.723095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e818bc5a9699'
down_revision: Union[str, Sequence[str], None] = '0904c596e780'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
