"""добавлена строка релатионшип в табл лайки для связи с юзером

Revision ID: f6e2dc6e7307
Revises: 82cc660730bd
Create Date: 2025-07-07 12:40:25.994481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6e2dc6e7307'
down_revision: Union[str, Sequence[str], None] = '82cc660730bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
